(package "pkg-dm"
         "0.1.0"
         "Package dependencies management")

(website-url "https://github.com/jcs-elpa/pkg-dm")
(keywords "maint")

(package-file "pkg-dm.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "28.1")
(depends-on "elenv")
(depends-on "msgu")
(depends-on "prt")
(depends-on "recentf-excl")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
